version: '3'
services:
  mongo:
    image: mongo
  node:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - 3050:3050
    volumes:
      - /app/node_modules
      - ./:/app
